#version: "3.7"

services:
  app:
      build: .
      ports:
        -  "8080:8080"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: sakib
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: sakib
    ports:
     - 5432:5432
